### ISSUE TITLE
Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by landland** [arunoda/meteor-up-legacy#371]
hey @arunoda, this is a new issue that just started happening. Seeing this in the mup logs

> Error: listen EADDRINUSE
> at errnoException (net.js:905:11)
>     at Server._listen2 (net.js:1043:14)
>     at listen (net.js:1065:10)
>     at net.js:1147:9
> at dns.js:72:18
>     at process._tickCallback (node.js:442:13)
> error: Forever detected script exited with code: 7
> error: Script restart attempt #54

Looks like there are multiple node processes. One by `root` and another by `meteorus`

![image](https://cloud.githubusercontent.com/assets/2052804/7126404/e6928906-e206-11e4-8f90-34788b639517.png)

The only way to stop it is to power cycle the droplet (digital ocean).

Not sure what's going on here. Any ideas? Here's my mup.json

```
{
    // Server authentication info
    "servers": [{
        "host": "<ip>",
        "username": "root",
        "password": "blah"
        // or pem file (ssh based authentication)
        //"pem": "~/.ssh/id_rsa"
    }],

    // Install MongoDB in the server, does not destroy local MongoDB on future setup
    "setupMongo": true,

    // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
    "setupNode": true,

    // WARNING: If nodeVersion omitted will setup 0.10.31 by default. Do not use v, only version number.
    "nodeVersion": "0.10.36",

    // Install PhantomJS in the server
    "setupPhantom": true,

    // Application name (No spaces)
    "appName": "aoscale1",

    // Location of app (local directory)
    "app": "/Users/landland/Documents/development/ao",

    // Configure environment
    "env": {
        "PORT": 80,
        // "ROOT_URL": "<ip>",
        "MONGO_URL": "<mongourl>",
        "MONGO_OPLOG_URL": "<oplog>",
        "MAIL_URL": "<mail>",
        "DISABLE_WEBSOCKETS": 1
    },

    // Meteor Up checks if the app comes online just after the deployment
    // before mup checks that, it will wait for no. of seconds configured below
    "deployCheckWaitTime": 15
}
```

I upgraded to latest mup version but same thing.

**Comment by benlwong** [comment]
I am getting the same error after upgrade Meteor to the latest version (1.1.0.2).  Then I tried upgrading to the latest mup version and node.js (0.10.36) and still no luck.  Not sure how I can debug this further.  Here is the error I am getting:

``` code
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickDomainCallback (node.js:486:13)
error: Forever detected script exited with code: 8
error: Script restart attempt #10
```

**Comment by benlwong** [comment]
Okay, my error is resolved.  Apparently, I had problem trying to deploy and run the app, and had to change the port to 80 (thinking that was the problem).  Then I upgraded mup and node.js to 0.10.36 and didn't change the port back to 3001.  Once I did that, it worked.  My EADDRINUSE problem was simply because it was set to port 80 (used by Nginx of course).  Duh.

**Comment by landland** [comment]
@benlwong can you elaborate on how you resolved this? Do you mean you changed the env.PORT in mup.json to 3001 and that fixed your problem? That doesn't seem to fix it over here for me.

**Comment by benlwong** [comment]
Sure, but honestly, I am a little fuzzy what all happened.  Basically, after I upgraded Meteor to 1.1.0.2 and tried to deploy the app with mup, I started getting an error that said "Meteor requires Node v0.10.36 or later.  I then tried to upgrade node.js using mup but it was giving some error about port 3001 being used.  That's when I tried to change the port to 80 in the mup.json file.  The other problem I was struggling with was mup doesn't appear to able to upgrade node.js.  I then tried to upgrade node.js manually and tried a bunch of other things.  After I finally got it upgraded to 0.10.36 and make sure there is no duplicate node.js install on the box, I started getting the EADDRINUSE error.  I finally realized that I switched the port 80 to 3001 earlier and it was conflicting with Nginx since it is using port 80 to serve the web.  After I switched it back to 3001, everything was working again.

Are you using Nginx as the web server?  If so, then I think your mup.json file should have 3001 as the port (not 80).

**Comment by landland** [comment]
This is happening on all of my servers, even the ones without nginx so I don't think it is related. But I did change the port on all of them to 3001 and other values to no avail.

But I did follow similar steps as you. Upgraded Meteor, then upgraded node to v0.10.36 and deployed. I have done this in the past without any issues though, so I'm not sure what's different this time.

**Comment by landland** [comment]
@benlwong if you deploy a second time, is everything ok? It is pretty consistent over here that if I deploy one time using a port (say 3001), everything is fine. If I deploy again on port 3001, I get the same issue.

**Comment by benlwong** [comment]
Yes, I redeployed a couple times yesterday and all seem to be fine.  I noticed you have "setupNode" as true, not sure that might be an issue.  Probably not, but just throwing some ideas out there.

**Comment by landland** [comment]
Ah good find, but that wasn't it. Rats! Back to the drawing board. @arunoda any clues?

**Comment by benlwong** [comment]
Sorry, I tried!  Let us know when you figured it out.  BTW, have you try running the deploy in debug mode (e.g. DEBUG=\* mup deploy)?  Good luck!

**Comment by landland** [comment]
right, I should have added that

```

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Building Started: /Users/landland/Documents/development/aoprocessor

Started TaskList: Deploy app 'aoprocessor' (linux)
[ip] - Uploading bundle
  nodemiral:sess:ip copy file - src: /tmp/7301eade-62c8-4da8-865f-a447244ef04f/bundle.tar.gz, dest: /opt/aoprocessor/tmp/bundle.tar.gz, vars: undefined +0ms
  nodemiral:sess:ip spawning command- sshpass -p pw scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/7301eade-62c8-4da8-865f-a447244ef04f/bundle.tar.gz root@ip:/opt/aoprocessor/tmp/bundle.tar.gz +1ms
  nodemiral:sess:ip spawn completed - code: 0 - 
    stdout:         stderr +30s Warning: Permanently added 'ip' (RSA) to the list of known hosts.

[ip] ✔ Uploading bundle: SUCCESS
[ip] - Setting up Environment Variables
  nodemiral:sess:ip copy file - src: /usr/local/lib/node_modules/mup/templates/linux/env.sh, dest: /opt/aoprocessor/config/env.sh, vars: {"env":{"PORT":3000,"ROOT_URL":"http://blah","MONGO_URL":"mongodb://private","MONGO_OPLOG_URL":"mongodb://oplog","MAIL_URL":"smtp://mail/","METEOR_SETTINGS":"{\"public\":{}}","CLUSTER_ENDPOINT_URL":"http://ip:3000"},"appName":"aoprocessor"} +2ms
  nodemiral:sess:ip spawning command- sshpass -p pw scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/axUMvzwrWXTLYeKxR root@ip:/opt/aoprocessor/config/env.sh +4ms
  nodemiral:sess:ip spawn completed - code: 0 - 
    stdout:         stderr +25s Warning: Permanently added 'ip' (RSA) to the list of known hosts.

[ip] ✔ Setting up Environment Variables: SUCCESS
[ip] - Invoking deployment process
  nodemiral:sess:ip execute - command: #!/bin/bash

# utilities
gyp_rebuild_inside_node_modules () {
  for npmModule in ./*; do
    cd $npmModule

    isBinaryModule="no"
    # recursively rebuild npm modules inside node_modules
    check_for_binary_modules () {
      if [ -f binding.gyp ]; then
        isBinaryModule="yes"
      fi

      if [ $isBinaryModule != "yes" ]; then
        if [ -d ./node_modules ]; then
          cd ./node_modules
          for module in ./*; do
            cd $module
            check_for_binary_modules
            cd ..
          done
          cd ../
        fi
      fi
    }

    check_for_binary_modules

    if [ $isBinaryModule == "yes" ]; then
      echo " > $npmModule: npm install due to binary npm modules"
      rm -rf node_modules
      if [ -f binding.gyp ]; then
        sudo npm install
        sudo node-gyp rebuild || :
      else
        sudo npm install
      fi
    fi

    cd ..
  done
}

rebuild_binary_npm_modules () {
  for package in ./*; do
    if [ -d $package/node_modules ]; then
      cd $package/node_modules
        gyp_rebuild_inside_node_modules
      cd ../../
    elif [ -d $package/main/node_module ]; then
      cd $package/node_modules
        gyp_rebuild_inside_node_modules
      cd ../../../
    fi
  done
}

revert_app (){
  if [[ -d old_app ]]; then
    sudo rm -rf app
    sudo mv old_app app
    sudo stop aoprocessor || :
    sudo start aoprocessor || :

    echo "Latest deployment failed! Reverted back to the previous version." 1>&2
    exit 1
  else
    echo "App did not pick up! Please check app logs." 1>&2
    exit 1
  fi
}


# logic
set -e

TMP_DIR=/opt/aoprocessor/tmp
BUNDLE_DIR=${TMP_DIR}/bundle

cd ${TMP_DIR}
sudo rm -rf bundle
sudo tar xvzf bundle.tar.gz > /dev/null
sudo chown -R ${USER} ${BUNDLE_DIR}

# rebuilding fibers
cd ${BUNDLE_DIR}/programs/server

if [ -d ./npm ]; then
  cd npm
  rebuild_binary_npm_modules
  cd ../
fi

if [ -d ./node_modules ]; then
  cd ./node_modules
  gyp_rebuild_inside_node_modules
  cd ../
fi

if [ -f package.json ]; then
  # support for 0.9
  sudo npm install
else
  # support for older versions
  sudo npm install fibers
  sudo npm install bcrypt
fi

cd /opt/aoprocessor/

# remove old app, if it exists
if [ -d old_app ]; then
  sudo rm -rf old_app
fi

## backup current version
if [[ -d app ]]; then
  sudo mv app old_app
fi

sudo mv tmp/bundle app

#wait and check
echo "Waiting for MongoDB to initialize. (5 minutes)"
. /opt/aoprocessor/config/env.sh
wait-for-mongo ${MONGO_URL} 300000

# restart app
sudo stop aoprocessor || :
sudo start aoprocessor || :

echo "Waiting for 15 seconds while app is booting up"
sleep 15

echo "Checking is app booted or not?"
curl localhost:${PORT} || revert_app

# chown to support dumping heapdump and etc
sudo chown -R meteoruser app
 +6ms
  nodemiral:sess:ip spawning command- sshpass -p pw ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@ip "bash -s" < /tmp/5FvT4TNqcDPJkdgIf +1ms
  nodemiral:sess:ip spawn completed - code: 0 - 
    stdout: 
> fibers@1.0.5 install /opt/aoprocessor/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

semver@4.1.0 node_modules/semver

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
└── has-ansi@0.1.0 (ansi-regex@0.2.1)

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

fibers@1.0.5 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
connected
aoprocessor stop/waiting
aoprocessor start/running, process 1400
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
<!DOCTYPE html>
<html>
<head>



<script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.1.0.2%22%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22http%3A%2F%2Fip%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22autoupdateVersion%22%3A%22baa1dd1c6ebdba8937b55153407e0928eb4622df%22%2C%22autoupdateVersionRefreshable%22%3A%225a561270f831ad5b029b48f1f1659e7682941b28%22%2C%22autoupdateVersionCordova%22%3A%22none%22%2C%22kadira%22%3A%7B%22appId%22%3A%22TSr2EPyJLEcdNNdjc%22%2C%22endpoint%22%3A%22https%3A%2F%2Fengine.kadira.io%22%2C%22clientEngineSyncDelay%22%3A10000%2C%22enableErrorTracking%22%3Atrue%7D%7D"));</script>

  <script type="text/javascript" src="/89e4f228491ea5d4075f531def8b13e24e1b31f1.js"></script>



<title>Hiiiiiiiii</title>
</head>
<body>

</body>
</html>
        stderr +44s Warning: Permanently added 'ip' (RSA) to the list of known hosts.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   864    0   864    0     0  14821      0 --:--:-- --:--:-- --:--:-- 14896

[ip] ✔ Invoking deployment process: SUCCESS
Completed TaskList: Deploy app 'aoprocessor' (linux)
```

I'm not seeing anything out of the ordinary, but yeah this results in the issue regardless.

**Comment by landland** [comment]
I resolved this by deleting the app on the server, running a mup setup and then deploy. Unfortunately I won't be able to help troubleshoot any further as the issue is resolved on my end, so I'll close this.
