### ISSUE TITLE
Can't use homelocation tilde notation after mupx 1.5.0

### ISSUE THREAD

**Issue by gabrielalmeida** [arunoda/meteor-up-legacy#499]
Hi,

As `README` just pointed since previous versions tilde notation should be replaced by `HOME` path.

After updating to `1.5.0` `mup.json` with:

`"app": "~/Dev/meteor-app-here/",`

Running `mupx` says:

`Invalid configuration file mup.json: There is no meteor app in the current app path.`

Using full path just works:

`"app": "/Users/gbr/Dev/meteor-app-here/",`

**Comment by arunoda** [comment]
I'll have a look on this.

**Comment by arunoda** [comment]
Did a fix. (v1.5.1)
It should be working  now. Open again if it's not.

**Comment by gabrielalmeida** [comment]
Great! Works as expected on v1.5.1.

Thanks

**Comment by sarkistlt** [comment]
i still have issue with (Invalid configuration file mup.json: There is no meteor app in the current app path.)
and it doesn't work wherever i use, with ~ or full path. i just have no idea what to do with it

**Comment by rawinazih** [comment]
after trying to deploy my app I faced the following error
[meteor.com] - Installing Docker
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 52.85.214.82:22
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1057:14)
